// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { definePrismaConfig } from 'prisma/config';
import {
  defineConfig as ormConfig,
  prisma7Schema,
} from '@prisma/orm-postgres/config';

export default definePrismaConfig({
  orm: ormConfig({
    contract: prisma7Schema('prisma/schema.prisma'),
    output: 'prisma',
    db: {
      connection: process.env['DATABASE_URL']!,
    },
    migrations: {
      dir: 'prisma/migrations',
    },
  }),
});
